renamed, documented and slightly refactored lbvector functions
doldecomp/melee pull request #240
Opened 2022-01-08 17:51 UTC by Ka-lua

I gave those func_1234asdf functions some descriptive names and renamed some variables, but someone has to check if it OK compiles because I still can't build the project properly (even in vanilla state).

I renamed all occurences of those functions in the *s, *.c and *.h, I hope that's all that has to be done for renaming functions.

2022-01-09 00:44 UTC, Ka-lua commented
The PR doesn't OK yet (my build setup works now after downgrading to devkitPPC r39), I'll update the PR with a working version later.

2022-01-11 03:50 UTC, PsiLupan requested changes
Left some general comments on the style. I directed it at specific instances, but I mean for them to apply to everything.

2022-01-11 03:50 UTC, PsiLupan commented on asm/melee/cm/camera.s
> +/* 80030BFC 0002D7DC  4B FD D6 15 */	bl lbvector_project_world_to_screen_coord
Let's stick to shorter names and convention of something like:
lbvector_WorldToScreen

2022-01-11 03:50 UTC, PsiLupan commented on asm/melee/cm/camera.s
> +/* 80030D50 0002D930  4B FD DA E9 */	bl lbvector_some_camera_vector_computation
I'm not sure calling this a camera vector computation is any more descriptive and is potentially misleading if it's used elsewhere.

Just stick to lbvector_8000E838

2022-01-11 03:50 UTC, PsiLupan commented on asm/melee/ft/chara/ftfox.s
> +/* 800E7948 000E4528  4B F2 5E 49 */	bl lbvector_angle_xy
Let's try
lbvector_AngleXY

2022-01-13 02:49 UTC, merged