[WIP] ftMasterHand
doldecomp/melee pull request #341
Opened 2022-04-02 15:35 UTC by BR-

2022-04-04 15:27 UTC, PsiLupan commented
Go ahead and put these in a ftMasterHand folder when you get the chance, since I'll ask for that later.

2022-04-08 20:44 UTC, r-burns commented on Makefile
> +GENERATE_MAP ?= 1
don't forget to disable this before merging ;)

2022-04-25 17:56 UTC, PsiLupan requested changes
Mostly just want you to get ```return;``` in the stub functions so they aren't just single line to be explicit about what they're doing.

2022-04-25 17:56 UTC, PsiLupan commented on src/melee/ft/chara/ftMasterHand/ftMasterHand_22.c
> +    if (
Please fix this spacing and just do:
```
if (--r31_ft_userdata->x2364 <= 0.0f && r31_ft_userdata->x2200_ftcmd_var0)
```

2022-04-25 17:56 UTC, PsiLupan commented on src/melee/ft/chara/ftMasterHand/ftMasterHand_25.c
> +void lbl_80154E74(HSD_GObj* gobj) {
Just put a ```return;```

2022-04-25 17:56 UTC, PsiLupan commented on src/melee/ft/chara/ftMasterHand/ftMasterHand_27.c
> +void lbl_80155190(HSD_GObj* gobj) {
Another ```return;```

2022-04-25 17:56 UTC, PsiLupan commented on src/melee/ft/chara/ftMasterHand/ftMasterHand_28.c
> +void lbl_801552F4(HSD_GObj* gobj) {
Another ```return;```

2022-04-26 01:37 UTC, BR- commented
`gawk -i inplace '/{$/ { empty = 1; print; next; } /^}$/ { if (empty == 1) print("    return;"); } 1 { empty = 0; print }' src/melee/ft/chara/ftMasterHand/ftMasterHand_*.c`

2022-04-26 02:43 UTC, merged